[package]
name = "only-semantic"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Semantic analysis for the only task language."

[dependencies]
only-diagnostic.workspace = true
only-syntax.workspace = true

smol_str.workspace = true
text-size.workspace = true
