[workspace]
members = [
    "crates/diagnostic",
    "crates/cli",
    "crates/syntax",
    "crates/semantic",
    "crates/engine",
    "crates/lsp",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/KercyDing/only"
documentation = "https://github.com/KercyDing/only"
readme = "README.md"

[workspace.dependencies]
anstyle = "1.0"
clap = { version = "4.6", features = ["color", "std", "string"] }
deno_task_shell = "0.33"
logos = "0.16"
miette = { version = "7.6", features = ["fancy"] }
minreq = { version = "3", default-features = false, features = ["https-rustls"] }
rowan = "0.17"
self-replace = "1.5"
sha2 = "0.11"
smol_str = "0.3"
text-size = "1.1"
tokio = { version = "1.53", features = ["rt"] }
winnow = "1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
debug = false
panic = "abort"
incremental = false
