[workspace]
members = [
    "crates/diagnostic",
    "crates/cli",
    "crates/syntax",
    "crates/semantic",
    "crates/engine",
    "crates/lsp",
]
resolver = "2"

[workspace.package]
version = "0.5.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/KercyDing/only"
documentation = "https://github.com/KercyDing/only"
readme = "README.md"

[workspace.dependencies]
only-diagnostic = { version = "0.5.1", path = "crates/diagnostic" }
only-engine = { version = "0.5.1", path = "crates/engine" }
only-semantic = { version = "0.5.1", path = "crates/semantic" }
only-syntax = { version = "0.5.1", path = "crates/syntax" }

anstyle = "1.0"
anstream = "1.0"
clap = { version = "4.6", features = ["color", "std", "string"] }
ctrlc = "3.5"
deno_task_shell = "0.33"
libc = "0.2"
portable-pty = "0.9"
logos = "0.16"
miette = { version = "7.6", features = ["fancy"] }
minreq = { version = "3", default-features = false }
rowan = "0.17"
self-replace = "1.5"
sha2 = "0.11"
smol_str = "0.3"
text-size = "1.1"
terminal_size = "0.4"
tokio = { version = "1.53", features = ["rt"] }
winnow = "1.0"
windows-sys = "0.61"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
debug = false
panic = "abort"
incremental = false
