[package]
name = "only"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
description = "A deterministic cross-platform task runner built on a staged language pipeline."
categories = ["command-line-utilities", "development-tools::build-utils"]
keywords = ["onlyfile", "task", "runner", "minimalist", "cli"]

[lib]
name = "only"
path = "src/lib.rs"

[[bin]]
name = "only"
path = "src/main.rs"

[dependencies]
only-diagnostic.workspace = true
only-engine.workspace = true
only-semantic.workspace = true
only-syntax.workspace = true

self-replace.workspace = true
sha2.workspace = true
anstyle.workspace = true
anstream.workspace = true
clap.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
minreq = { workspace = true, features = ["https-rustls"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
minreq = { workspace = true, features = ["https-native-tls"] }
