[package]
name = "only-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Language Server Protocol support for the only task language."

[dependencies]
only-diagnostic.workspace = true
only-semantic.workspace = true
only-syntax.workspace = true

text-size.workspace = true
tokio = { workspace = true, features = ["io-std", "macros", "rt-multi-thread"] }
tower-lsp = "0.20"
