[package]
name = "only-syntax"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Syntax parsing and CST construction for the only task language."

[dependencies]
only-diagnostic = { version = "0.3.0", path = "../diagnostic" }

logos.workspace = true
rowan.workspace = true
smol_str.workspace = true
text-size.workspace = true
winnow.workspace = true
